name: Bug Report2
Bug_report:
  proyecto: Nombre_del_proyecto
  id: Identificador_del_caso_de_prueba
  dia_del_reporte: Fecha_del_reporte
  dispositivo_navegador: Ubuntu-Windows - Chrome-Firefox-Edge
  tipo_de_defecto: Visual-Funcional-Contenido-Crash-Performance
  prioridad: Alta/Media/Baja
  asignado_a: FrontEnd-Backend-Diseño

  pasos_de_reproduccion:
    pre_requisitos: n/a
    - Ingresar URL:
    - Segundo paso:
    - [...]

  resultado_esperado: Descripcion_del_resultado_esperado

  resultado_obtenido: Descripcion_del_resultado_obtenido

  capturas_de_pantalla: [adjuntos_de_imagen_o_video]

  tester_qa: Nombre_del_tester
