name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |

  - type: text
    id: bug-report-id
    attributes:
      label: ID
      description: 
      placeholder: 
    validations:
      required: true

  - type: date
    id: bug-report-date
    attributes:
      label: Dia del Reporte
      description: 
      placeholder: Elegir Fecha
    validations:
      required: true

  - type: dropdown
    id: dispositivo-navegador
    attributes:
      label: Dispositivo / Navegador 
      multiple: true
      options:
        - PC - Windows
        - PC - Ubuntu
        - Mobile - Android
        - Mobile - IOS
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: dropdown
    id: tipo-de-defecto
    attributes:
      label: Tipo de defecto
      description: 
      options:
        - Visual
        - Funcional
        - Contenido
        - Crash
        - Performance
      default: 0
    validations:
      required: true

  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad
      description: 
      options:
        - Baja
        - Media
        - Alta
      default: 0
    validations:
      required: true

  - type: dropdown
    id: asignado-a
    attributes:
      label: Asignado a
      description: 
      options:
        - Visual
        - Funcional
        - Contenido
        - Crash
        - Performance
      default: 0
    validations:
      required: true

  - type: textarea
    id: pasos-de-reproduccion
    attributes:
      label: Pasos de Reproduccion
      description: si se requieren pre-requisitos agregarlos antes de los pasos de reproduccion 
      placeholder: |
        Pre-requisitos: N/A
        1. Ingresar URL:
        2. Segundo paso:
        3. [...]

  - type: textarea
    id: resultado-esperado
    attributes:
      label: Resultado Esperado
      description: Describir el resultado esperado

  - type: textarea
    id: resultado-obtenido
    attributes:
      label: Resultado Obtenido
      description: Describir el resultado obtenido

  - type: textarea
    id: capturas-de-pantalla
    attributes:
      label: Screenshots or Videos
      description: Adjuntar capturas de pantalla o videos relevantes.

  - type: input
    id: tester-qa
    attributes:
      label: Tester QA
      description: 
      placeholder: Nombre del tester
    validations:
      required: true
