name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:

  - type: dropdown
    id: version
    attributes:
      label: Tipo de Defecto
      options:
        - Funcional
        - Visual
        - Crash
        - Performance
        - Contenido
    validations:
      required: true

  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad
      description: 
      options:
        - Baja
        - Media
        - Alta
      default: 0
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Dispositivo / Navegador
      description: Elegir disposito y navegador
      multiple: true
      options:
        - PC - Windows
        - PC - Ubuntu
        - Mobile - Android
        - Mobile - IOS
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: textarea
    id: pasos-de-reproduccion
    attributes:
      label: Pasos de Reproduccion
      description: si se requieren pre-requisitos agregarlos antes de los pasos de reproduccion 
      placeholder: |
        Pre-requisitos: N/A
        1. Ingresar URL:
        2. Segundo paso:
        3. [...]

  - type: textarea
    id: resultado_esperado
    attributes:
      label: Expected Result
      description: Describe what you expected to happen.

  - type: textarea
    id: resultado_obtenido
    attributes:
      label: Actual Result
      description: Describe what actually happened.

  - type: textarea
    id: capturas_de_pantalla
    attributes:
      label: Screenshots or Videos
      description: Attach any relevant screenshots or videos.

  - type: input
    id: tester_qa
    attributes:
      label: QA Tester
      description: Name of the QA Tester who reported the bug.
      placeholder: Tester's name
    validations:
      required: true
