name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:

  - type: dropdown
    id: version
    attributes:
      label: Tipo de Defecto
      options:
        - Funcional
        - Visual
        - Crash
        - Performance
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Dispositivo / Navegador
      multiple: true
      options:
        - PC - Windows
        - PC - Ubuntu
        - Mobile - Android
        - Mobile - IOS
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: textarea
    id: pasos_de_reproduccion
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Ingresar URL:
        2. Segundo paso:
        3. [...]

  - type: textarea
    id: resultado_esperado
    attributes:
      label: Expected Result
      description: Describe what you expected to happen.

  - type: textarea
    id: resultado_obtenido
    attributes:
      label: Actual Result
      description: Describe what actually happened.

  - type: textarea
    id: capturas_de_pantalla
    attributes:
      label: Screenshots or Videos
      description: Attach any relevant screenshots or videos.

  - type: input
    id: tester_qa
    attributes:
      label: QA Tester
      description: Name of the QA Tester who reported the bug.
      placeholder: Tester's name
    validations:
      required: true
