name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |

  - type: text
    id: bug-report-id
    attributes:
      label: ID
      description: 
      placeholder: 
    validations:
      required: true

  - type: date
    id: bug-report-date
    attributes:
      label: Dia del Reporte
      description: 
      placeholder: Elegir Fecha
    validations:
      required: true

  - type: dropdown
    id: Dispositivo / Navegador
    attributes:
      label: Dispositivo / Navegador 
      multiple: true
      options:
        - PC - Windows
        - PC - Ubuntu
        - Mobile - Andorid
        - Mobile - IOS
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: dropdown
    id: Tipo de Defecto
    attributes:
      label: Tipo de defecto
      description: 
      options:
        - Visual
        - Funcional
        - Contendio
        - Crash
        - Performance
      default: 0
    validations:
      required: true

  - type: dropdown
    id: Prioridad
    attributes:
      label: Prioridad
      description: 
      options:
        - Baja
        - Media
        - Alta
      default: 0
    validations:
      required: true

        - type: dropdown
    id: Asignado a
    attributes:
      label: Asignado a
      description: 
      options:
        - Visual
        - Funcional
        - Contendio
        - Crash
        - Performance
      default: 0
    validations:
      required: true

  # - type: textarea
  #   id: logs
  #   attributes:
  #     label: Relevant log output
  #     description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
  #     render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: textarea
    id: pasos_de_reproduccion
    attributes:
      label: Pasos de Reproduccion
      description: si se requieren pre-requisitos agregarlos antes de los pasos de reproduccion 
      placeholder: |
      Pre-requisitos: N/A
        1. Ingresar URL:
        2. Segundo paso:
        3. [...]

  - type: textarea
    id: resultado_esperado
    attributes:
      label: Resultado Esperado
      description: Describir el resultado esperado

  - type: textarea
    id: resultado_obtenido
    attributes:
      label: Resultado Obtenido
      description: Describir el reusltado obtenido

  - type: textarea
    id: capturas_de_pantalla
    attributes:
      label: Screenshots or Videos
      description: Attach any relevant screenshots or videos.

  - type: input
    id: tester_qa
    attributes:
      label: Tester QA
      description: 
      placeholder: Nombre del tester
    validations:
      required: true
